int openRequestChecker();
int NewAccount();
void clear_buffer();
int IsValidDouble(char str [256]);
void OpenBankAcount(double ammount);
void BalanceCheck(int numberOfaccount);
 void Diposet(int numberOfaccount, double diposet);
void Withdraw(int numberOfaccount, double withDraw );
void AddRate(double ratePre);
void PrintStatus();
void Close(int numberOfaccount);
int Exit();
